CREATE DATABASE tasksdb;

CREATE TABLE IF NOT EXISTS TB_EEC_users(
    id SERIAL PRIMARY KEY,
    nickname VARCHAR(12) NOT NULL,
    playtime INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS TB_EEC_posts(
    id SERIAL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    content TEXT,
    type INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);